### ISSUE TITLE
Not easy_install(ation ?)

### ISSUE THREAD

**Issue by diegozea** [mdipierro/mdpcl#3]
##### I try using easy_install:

sudo easy_install mdpcl
/usr/bin/easy_install:5: UserWarning: Module dap was already imported from None, but /usr/lib/python2.7/dist-packages is being added to sys.path
  from pkg_resources import load_entry_point
Searching for mdpcl
Best match: mdpcl 0.7
Adding mdpcl 0.7 to easy-install.pth file
Using /usr/local/lib/python2.7/dist-packages
Processing dependencies for mdpcl
Finished processing dependencies for mdpcl
##### But i don't get any module :/

Python 2.7.3 (default, Sep 26 2012, 21:51:14) 
[GCC 4.7.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > import mdpcl
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > ImportError: No module named mdpcl
##### When I try with pip install, I get error with meta, but meta is installed:

sudo pip install mdpcl
/usr/bin/pip:5: UserWarning: Module dap was already imported from None, but /usr/lib/python2.7/dist-packages is being added to sys.path
  from pkg_resources import load_entry_point
Downloading/unpacking mdpcl
  Downloading mdpcl-0.7.tar.gz
  Running setup.py egg_info for package mdpcl
    /usr/lib/python2.7/dist-packages/setuptools/command/install_scripts.py:3: UserWarning: Module dap was already imported from None, but /usr/lib/python2.7/dist-packages is being added to sys.path
      from pkg_resources import Distribution, PathMetadata, ensure_directory

```
file meta.py (for module meta) not found
```

Installing collected packages: mdpcl
  Running setup.py install for mdpcl
    /usr/lib/python2.7/dist-packages/setuptools/command/install_scripts.py:3: UserWarning: Module dap was already imported from None, but /usr/lib/python2.7/dist-packages is being added to sys.path
      from pkg_resources import Distribution, PathMetadata, ensure_directory
    file meta.py (for module meta) not found
    file meta.py (for module meta) not found
    changing mode of build/scripts-2.7/mdpcl.py from 644 to 755
    warning: install_lib: 'build/lib.linux-x86_64-2.7' does not exist -- no Python modules to install

```
file meta.py (for module meta) not found
changing mode of /usr/local/bin/mdpcl.py to 755
file meta.py (for module meta) not found
```

Successfully installed mdpcl
Cleaning up...
##### But meta is installed

Python 2.7.3 (default, Sep 26 2012, 21:51:14) 
[GCC 4.7.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > import mdpcl
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > ImportError: No module named mdpcl
> > > import meta
##### Is normal that installation appends in /usr/local/bin and not in /usr/local/lib/python2.7/dist-packages/ or another python lib directory?

sudo pip uninstall mdpcl
/usr/bin/pip:5: UserWarning: Module dap was already imported from None, but /usr/lib/python2.7/dist-packages is being added to sys.path
  from pkg_resources import load_entry_point
Uninstalling mdpcl:
  /usr/local/bin/mdpcl.py
  /usr/local/lib/python2.7/dist-packages/mdpcl-0.7.egg-info
Proceed (y/n)?  y

**Comment by mdipierro** [comment]
I do not know either. I can reproduce the problem. The problem is with my build. For now just download mdpcl.py and that should be all you need.
